=== bicefish/tb-api-doc/examples/export.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://interface.technikboerse.com/XMLSchema" xmlns="http://interface.technikboerse.com/XMLSchema" elementFormDefault="qualified">
  <xs:element name="exchange">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="senderName" maxOccurs="1" minOccurs="1" type="xs:string"/>
        <xs:element name="exportDate" maxOccurs="1" minOccurs="1" type="xs:dateTime"/>
        <xs:element name="transferMode" maxOccurs="1" minOccurs="1" type="transferModeType"/>
        <xs:element name="backLogDays" maxOccurs="1" minOccurs="0" type="xs:int"/>
        <xs:element maxOccurs="1" ref="dealersDeleted" minOccurs="0"/>
        <xs:element maxOccurs="1" ref="adsDeleted" minOccurs="0"/>
        <xs:element maxOccurs="unbounded" ref="dealers" minOccurs="0"/>
        <xs:element name="validation" maxOccurs="1" minOccurs="0" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="dealersDeleted">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="deleteInfo" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="deleteInfo">
      <xs:complexType mixed="true">
          <xs:attribute name="guid" type="msGUID"/>
          <xs:attribute name="id" type="xs:long"/>
      </xs:complexType>
  </xs:element>
  <xs:element name="adsDeleted">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="deleteInfo" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="dealers">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="dealer"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="dealer">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="info" minOccurs="0"/>
        <xs:element maxOccurs="unbounded" ref="phone" minOccurs="0"/>
        <xs:element maxOccurs="unbounded" ref="mobile" minOccurs="0"/>
        <xs:element maxOccurs="unbounded" ref="fax" minOccurs="0"/>
        <xs:element name="created" type="xs:dateTime" maxOccurs="1" minOccurs="0"/>
        <xs:element name="modified" type="xs:dateTime" maxOccurs="1" minOccurs="0"/>
        <xs:element maxOccurs="unbounded" ref="ads" minOccurs="0"/>
        <xs:element maxOccurs="unbounded" ref="contacts" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="guid" use="required" type="msGUID"/>
      <xs:attribute name="id" use="optional" type="xs:long"/>
      <xs:attribute name="pguid" use="optional" type="msGUID"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="phone">
	<xs:complexType mixed="true">
	  <xs:attribute name="international_dialing_code" use="optional" type="xs:string"/>
	  <xs:attribute name="area_code" use="optional" type="xs:string"/>
	  <xs:attribute name="number" use="optional" type="xs:string"/>
          <xs:attribute name="whatsapp" use="optional" type="xs:string"/>
	</xs:complexType>
  </xs:element>
  <xs:element name="mobile">
	<xs:complexType mixed="true">
	  <xs:attribute name="international_dialing_code" use="optional" type="xs:string"/>
	  <xs:attribute name="area_code" use="optional" type="xs:string"/>
	  <xs:attribute name="number" use="optional" type="xs:string"/>
          <xs:attribute name="whatsapp" use="optional" type="xs:string"/>
	</xs:complexType>
  </xs:element>
  <xs:element name="fax">
	<xs:complexType mixed="true">
	  <xs:attribute name="international_dialing_code" use="optional" type="xs:string"/>
	  <xs:attribute name="area_code" use="optional" type="xs:string"/>
	  <xs:attribute name="number" use="optional" type="xs:string"/>
	</xs:complexType>
  </xs:element>
  <xs:element name="ads">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="ad" minOccurs="0"/>
	  </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="contacts">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="contact" minOccurs="0"/>
	  </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="contact">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="gender" type="xs:string" maxOccurs="1" minOccurs="0"/>
        <xs:element name="first_name" type="xs:string" maxOccurs="1" minOccurs="1"/>
        <xs:element name="last_name" type="xs:string" maxOccurs="1" minOccurs="1"/>
        <xs:element maxOccurs="unbounded" ref="phone" minOccurs="0"/>
        <xs:element maxOccurs="unbounded" ref="mobile" minOccurs="0"/>
        <xs:element maxOccurs="unbounded" ref="fax" minOccurs="0"/>
        <xs:element name="email" type="xs:string" maxOccurs="1" minOccurs="1"/>
        <xs:element name="image" type="xs:string" maxOccurs="1" minOccurs="1"/>
        <xs:element maxOccurs="unbounded" ref="responsibilities" minOccurs="0"/>
        <xs:element maxOccurs="unbounded" ref="languages_iso_639_1" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:long"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="ad">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="info" minOccurs="0"/>        
        <xs:element maxOccurs="unbounded" ref="contact_ids" minOccurs="0"/>
        <xs:element maxOccurs="1" ref="price" minOccurs="0"/>        
        <xs:element name="canonical_url" type="xs:string" maxOccurs="1" minOccurs="0"/>
        <xs:element ref="canonical_urls" maxOccurs="unbounded" minOccurs="0"/>
        <xs:element name="created" type="xs:dateTime" maxOccurs="1" minOccurs="1"/>
        <xs:element name="modified" type="xs:dateTime" maxOccurs="1" minOccurs="1"/>
        <xs:element ref="images"/>
        <xs:element maxOccurs="1" ref="video" minOccurs="0"/>
        <xs:element maxOccurs="1" ref="auction" minOccurs="0"/>
        <xs:element maxOccurs="1" ref="purchase" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="guid" use="required" type="msGUID"/>
      <xs:attribute name="id" use="required" type="xs:long"/>
      <xs:attribute name="category_id" use="required" type="xs:int"/>
      <xs:attribute name="category_name" use="optional" type="xs:string"/>
      <xs:attribute name="parent_category_name" use="optional" type="xs:string"/>
      <xs:attribute name="ad_type" use="optional" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="canonical_urls">
    <xs:complexType>
      <xs:sequence>
         <xs:element ref="canonical_url" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="images">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="30" ref="image"/>
      </xs:sequence>
      <xs:attribute name="md5" use="optional" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="responsibilities">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="responsibility" maxOccurs="unbounded" minOccurs="0" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="languages_iso_639_1">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="language" maxOccurs="unbounded" minOccurs="0" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="contact_ids">
    <xs:complexType>
      <xs:sequence>
       <xs:element name="contact_id" type="xs:long" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="image">
      <xs:complexType mixed="true">
          <xs:attribute name="type" type="xs:string"/>
          <xs:attribute name="image_name" use="required" type="xs:string"/>
      </xs:complexType>
  </xs:element>
  <xs:element name="canonical_url">
      <xs:complexType mixed="true">
          <xs:attribute name="languages_iso_639_1" use="required" type="xs:string"/>
      </xs:complexType>
  </xs:element>
  <xs:element name="info">
    <xs:complexType mixed="true">
      <xs:attribute name="id" use="required" type="xs:int"/>
      <xs:attribute name="name" use="optional" type="xs:string"/>
      <xs:attribute name="unit" use="optional" type="xs:string"/>
      <xs:attribute name="data_type" use="optional" type="xs:string"/>
      <xs:attribute name="plain" use="optional" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="price">
    <xs:complexType mixed="true">
      <xs:attribute name="currency" use="required" type="xs:string"/>
      <xs:attribute name="taxtype" use="required" type="taxtype"/>
      <xs:attribute name="tax_percentage" use="required" type="percentage"/>
      <xs:attribute name="euro_gross_price_value" use="optional" type="xs:string"/>
      <xs:attribute name="special_price" use="optional" type="xs:string"/>
      <xs:attribute name="price_unit" use="optional" type="xs:int"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="video">
    <xs:complexType mixed="true">
      <xs:attribute name="video_id" use="required" type="xs:string"/>
      <xs:attribute name="video_url" use="required" type="xs:string"/>
      <xs:attribute name="video_type" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="auction">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element maxOccurs="1" ref="price" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:int"/>
      <xs:attribute name="startdate" use="required" type="xs:dateTime"/>
      <xs:attribute name="enddate" use="required" type="xs:dateTime"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="purchase">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element maxOccurs="1" ref="price" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:int"/>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="percentage">
	<xs:restriction base="xs:float">
		<xs:minInclusive value="0.00"/>
		<xs:maxInclusive value="1.00"/>
	</xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="transferModeType">
	<xs:restriction base="xs:string">
	  <xs:enumeration value="full"/>
	  <xs:enumeration value="update"/>
	</xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="taxtype">
	<xs:restriction base="xs:string">
	  <xs:enumeration value="exclusive"/>
	  <xs:enumeration value="inclusive"/>
	  <xs:enumeration value="tax_cannot_be_stated_separately"/>
	</xs:restriction>
  </xs:simpleType>  
  <xs:simpleType name="msGUID">
      <xs:restriction base="xs:string">
          <xs:pattern value="(\{){0,1}[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}(\}){0,1}"/>
      </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== bicefish/tb-api-doc/examples/example_update_export.xml
<?xml version="1.0" encoding="UTF-8"?>
<exchange xmlns="http://interface.technikboerse.com/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://interface.technikboerse.com/xsd/export.xsd">
  <senderName>technikboerse</senderName>
  <exportDate>2012-05-04T13:31:42+02:00</exportDate>
  <transferMode>update</transferMode>
  <backLogDays>3</backLogDays>
  <dealersDeleted/>
  <adsDeleted/>
  <dealers>
    <!--49307908-->
    <dealer guid="81d32e91-9db3-5899-be2a-b4795fb56491" id="49307908">
      <info id="50500" name="company_name">dieMayrei GmbH</info>
      <info id="50501" name="street">Joseph-Gänsler-Str. 4</info>
      <info id="50502" name="zipcode">86609</info>
      <info id="50503" name="city">Donauwörth</info>
      <info id="50504" name="country_iso3166_1">DE</info>
      <info id="50505" name="phone">0049 (0) 1805826773</info>
      <info id="50506" name="mobile_phone">0049 12345</info>
      <info id="50507" name="email">tobias.beck@diemayrei.de</info>
      <info id="50509" name="contact_person">Herr Tobias Beck</info>
      <info id="50512" name="fax">0049 (0) 0906 7057777</info>
      <info id="50513" name="url">http://www.diemayrei.de</info>
      <info id="50516" name="logo"/>
      <info id="50517" name="type">commercial</info>
      <created>2008-07-11T00:00:00+02:00</created>
      <modified>2012-05-04T11:32:00+02:00</modified>
      <ads>
        <!--488091-->
        <ad guid="a8f1ad52-c2eb-5981-a627-4fb5226f1d71" id="488091" category_id="210" category_name="Mähdrescher" parent_category_name="Mähdrescher">
          <info id="50000" name="internal_ad_id" data_type="string"><![CDATA[1489]]></info>
          <info id="50001" name="manufacturer_name" data_type="enum">Claas</info>
          <info id="50002" name="model" data_type="string"><![CDATA[Lexion 480]]></info>
          <info id="50003" name="power" unit="PS" data_type="int">375</info>
          <info id="50004" name="year_of_manufacturer" data_type="int">2001</info>
          <info id="50005" name="operating_hours" data_type="int">1100</info>
          <info id="50011" name="location_info" data_type="string"><![CDATA[]]></info>
          <info id="50012" name="condition" data_type="enum">used</info>
          <info id="50016" name="description" data_type="string"><![CDATA[]]></info>
          <info id="50017" name="location_zipcode" data_type="string"><![CDATA[]]></info>
          <info id="50018" name="location_city" data_type="string"><![CDATA[]]></info>
          <info id="50020" name="is_customer_mission" data_type="boolean">0</info>
          <info id="2011" name="Klimaanlage" data_type="boolean">1</info>
          <info id="2030" name="Breite" unit="m" data_type="float">7,50</info>
          <info id="2031" name="Pendelausgleich" data_type="boolean">1</info>
          <info id="2033" name="Schneidwerkswagen" data_type="boolean">1</info>
          <info id="2035" name="Spreuverteiler" data_type="boolean">1</info>
          <info id="2036" name="Strohhäcksler" data_type="boolean">1</info>
          <info id="2037" name="Verlustmessung" data_type="boolean">1</info>
          <contact_ids>
            <contact_id>6268</contact_id>
            <contact_id>6538</contact_id>
          </contact_ids>
          <!--6.800.000 € (5.714.286 € zzgl. 19 % MwSt)-->
          <price currency="EUR" taxtype="inclusive" tax_percentage="0.190">6800000</price>
          <created>2005-09-19T15:57:32+02:00</created>
          <modified>2012-05-04T13:31:40+02:00</modified>
          <images>
            <image image_name="phpVf8xNQ.jpg"><![CDATA[http://interface.technikboerse.com/thumbnails/49307908/488091/phpVf8xNQ_400x300.jpg]]></image>
          </images>
        </ad>
        <!--488092-->
        <ad guid="2b688730-2da4-5767-a8f0-75aa24875111" id="488092" category_id="210" category_name="Mähdrescher" parent_category_name="Mähdrescher">
          <info id="50000" name="internal_ad_id" data_type="string"><![CDATA[0583]]></info>
          <info id="50001" name="manufacturer_name" data_type="enum">Claas</info>
          <info id="50002" name="model" data_type="string"><![CDATA[Lexion 460 Evo]]></info>
          <info id="50003" name="power" unit="PS" data_type="int">300</info>
          <info id="50004" name="year_of_manufacturer" data_type="int">2002</info>
          <info id="50005" name="operating_hours" data_type="int">1235</info>
          <info id="50011" name="location_info" data_type="string"><![CDATA[Donauwörth]]></info>
          <info id="50012" name="condition" data_type="enum">used</info>
          <info id="50017" name="location_zipcode" data_type="string"><![CDATA[]]></info>
          <info id="50018" name="location_city" data_type="string"><![CDATA[]]></info>
          <info id="50020" name="is_customer_mission" data_type="boolean">0</info>
          <info id="2011" name="Klimaanlage" data_type="boolean">1</info>
          <info id="2030" name="Breite" unit="m" data_type="float">7,50</info>
          <info id="2031" name="Pendelausgleich" data_type="boolean">1</info>
          <info id="2033" name="Schneidwerkswagen" data_type="boolean">1</info>
          <info id="2034" name="Siebkastenhangausgleich" data_type="boolean">1</info>
          <info id="2035" name="Spreuverteiler" data_type="boolean">1</info>
          <info id="2036" name="Strohhäcksler" data_type="boolean">1</info>
          <info id="2037" name="Verlustmessung" data_type="boolean">1</info>
          <contact_ids>
            <contact_id>6268</contact_id>
            <contact_id>6538</contact_id>
          </contact_ids>
          <!--Keine Angabe-->
          <price currency="EUR" taxtype="inclusive" tax_percentage="0.190">0</price>
          <created>2005-09-19T15:59:42+02:00</created>
          <modified>2012-05-04T13:31:40+02:00</modified>
          <images>
            <image image_name="phpIZES3N.jpg"><![CDATA[http://interface.technikboerse.com/thumbnails/49307908/488092/phpIZES3N_400x300.jpg]]></image>
          </images>
        </ad>
        <!--488093-->
        <ad guid="81a6b497-ee9f-5295-93a3-1ff919aa0f2f" id="488093" category_id="210" category_name="Mähdrescher" parent_category_name="Mähdrescher">
          <info id="50000" name="internal_ad_id" data_type="string"><![CDATA[0582]]></info>
          <info id="50001" name="manufacturer_name" data_type="enum">Claas</info>
          <info id="50002" name="model" data_type="string"><![CDATA[Lexion 460 Evo]]></info>
          <info id="50003" name="power" unit="PS" data_type="int">300</info>
          <info id="50004" name="year_of_manufacturer" data_type="int">2002</info>
          <info id="50005" name="operating_hours" data_type="int">1234</info>
          <info id="50011" name="location_info" data_type="string"><![CDATA[Donauwörth]]></info>
          <info id="50012" name="condition" data_type="enum">used</info>
          <info id="50016" name="description" data_type="string"><![CDATA[]]></info>
          <info id="50017" name="location_zipcode" data_type="string"><![CDATA[]]></info>
          <info id="50018" name="location_city" data_type="string"><![CDATA[]]></info>
          <info id="50020" name="is_customer_mission" data_type="boolean">0</info>
          <info id="2002" name="Allrad" data_type="boolean">1</info>
          <info id="2003" name="Autocontour" data_type="boolean">1</info>
          <info id="2004" name="Bordcomputer" data_type="boolean">1</info>
          <info id="2011" name="Klimaanlage" data_type="boolean">1</info>
          <info id="2017" name="Rapsschneidwerk" data_type="boolean">1</info>
          <info id="2019" name="Rapstrenner links" data_type="enum"><![CDATA[136]]></info>
          <info id="2020" name="Rapstrenner rechts" data_type="enum"><![CDATA[136]]></info>
          <info id="2030" name="Breite" unit="m" data_type="float">7,50</info>
          <info id="2031" name="Pendelausgleich" data_type="boolean">1</info>
          <info id="2033" name="Schneidwerkswagen" data_type="boolean">1</info>
          <info id="2034" name="Siebkastenhangausgleich" data_type="boolean">1</info>
          <info id="2035" name="Spreuverteiler" data_type="boolean">1</info>
          <info id="2036" name="Strohhäcksler" data_type="boolean">1</info>
          <info id="2037" name="Verlustmessung" data_type="boolean">1</info>
          <contact_ids>
            <contact_id>6268</contact_id>
            <contact_id>6538</contact_id>
          </contact_ids>
          <!--79.000 € (66.387 € zzgl. 19 % MwSt)-->
          <price currency="EUR" taxtype="inclusive" tax_percentage="0.190">79000</price>
          <created>2010-05-26T16:01:05+02:00</created>
          <modified>2012-05-04T13:31:41+02:00</modified>
          <images>
            <image image_name="53b7dd352ff4a245d215a808f3c48a3a.jpg"><![CDATA[http://interface.technikboerse.com/thumbnails/49307908/488093/53b7dd352ff4a245d215a808f3c48a3a_400x300.jpg]]></image>
          </images>
        </ad>
        <!--488096-->
        <ad guid="389e0960-ee40-5763-b3cc-1ef5ff926040" id="488096" category_id="210" category_name="Mähdrescher" parent_category_name="Mähdrescher">
          <info id="50000" name="internal_ad_id" data_type="string"><![CDATA[0291]]></info>
          <info id="50001" name="manufacturer_name" data_type="enum">Claas</info>
          <info id="50002" name="model" data_type="string"><![CDATA[DO 208 Mega II]]></info>
          <info id="50003" name="power" unit="PS" data_type="int">239</info>
          <info id="50004" name="year_of_manufacturer" data_type="int">1996</info>
          <info id="50005" name="operating_hours" data_type="int">2217</info>
          <info id="50011" name="location_info" data_type="string"><![CDATA[DE-86609 Donauwörth]]></info>
          <info id="50012" name="condition" data_type="enum">used</info>
          <info id="50016" name="description" data_type="string"><![CDATA[]]></info>
          <info id="50017" name="location_zipcode" data_type="string"><![CDATA[]]></info>
